version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern-stack-assessment
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0.2
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
